/**
 * Cross-validation test: TypeScript engine vs Python engine.
 *
 * Loads reference fixtures generated by the Python engine (generate_test_fixtures.py)
 * and verifies the TypeScript engine produces identical results at every step:
 * - Game state (pieces, balls, currentPlayer, touchedMask, hasPassed, lastKnightDst, ply)
 * - Legal moves (exact set)
 * - Terminal detection
 * - Winner
 * - Neural network tensor output (exact float values)
 */

import { describe, it, expect } from 'vitest';
import fixtures from './fixtures.json';
import {
  newGame,
  applyMove,
  isTerminal,
  getWinner,
  type EngineState,
} from '../state';
import { getLegalMoves } from '../moves';
import { stateToTensor } from '../tensor';
import { algebraicToSq } from '../bitboard';

// Move encoding helpers (duplicated to avoid circular deps in test)
function encodeMove(src: number, dst: number): number {
  return src * 56 + dst;
}

function algebraicToMove(s: string): number {
  if (s === 'end') return -1;
  const parts = s.split('-');
  return encodeMove(algebraicToSq(parts[0]), algebraicToSq(parts[1]));
}

interface FixtureState {
  pieces: [string, string]; // Strings to preserve precision
  balls: [string, string];
  currentPlayer: number;
  touchedMask: string;
  hasPassed: boolean;
  lastKnightDst: number;
  ply: number;
}

interface Snapshot {
  description: string;
  state: FixtureState;
  legalMoves: number[];
  tensor: number[];
  isTerminal: boolean;
  winner: number | null;
  moveApplied?: number;
  moveAlgebraic?: string;
}

interface Sequence {
  name: string;
  moves: string[];
  snapshots: Snapshot[];
}

interface Fixtures {
  description: string;
  sequences: Sequence[];
}

const data = fixtures as Fixtures;

// Compare TS engine state against Python reference
function assertStateEquals(ts: EngineState, py: FixtureState, _ctx: string): void {
  expect(ts.pieces[0]).toBe(BigInt(py.pieces[0]));
  expect(ts.pieces[1]).toBe(BigInt(py.pieces[1]));
  expect(ts.balls[0]).toBe(BigInt(py.balls[0]));
  expect(ts.balls[1]).toBe(BigInt(py.balls[1]));
  expect(ts.currentPlayer).toBe(py.currentPlayer);
  expect(ts.touchedMask).toBe(BigInt(py.touchedMask));
  expect(ts.hasPassed).toBe(py.hasPassed);
  expect(ts.lastKnightDst).toBe(py.lastKnightDst);
  expect(ts.ply).toBe(py.ply);
}

describe('Cross-validation: TypeScript vs Python engine', () => {
  for (const seq of data.sequences) {
    describe(seq.name, () => {
      it('matches state, legal moves, terminal, and winner at every step', () => {
        const state = newGame();

        // Check initial state
        const initial = seq.snapshots[0];
        assertStateEquals(state, initial.state, `${seq.name} initial`);

        const initialLegal = getLegalMoves(state).sort((a, b) => a - b);
        expect(initialLegal).toEqual(initial.legalMoves);
        expect(isTerminal(state)).toBe(initial.isTerminal);
        expect(getWinner(state)).toBe(initial.winner);

        // Apply each move and check
        for (let i = 0; i < seq.moves.length; i++) {
          const moveAlg = seq.moves[i];
          const move = algebraicToMove(moveAlg);
          const expected = seq.snapshots[i + 1];

          applyMove(state, move);
          const ctx = `${seq.name} after ${moveAlg} (step ${i + 1})`;

          assertStateEquals(state, expected.state, ctx);

          const legal = getLegalMoves(state).sort((a, b) => a - b);
          expect(legal).toEqual(expected.legalMoves);

          expect(isTerminal(state)).toBe(expected.isTerminal);
          expect(getWinner(state)).toBe(expected.winner);
        }
      });

      it('matches tensor output at every step', () => {
        const state = newGame();

        // Check initial tensor
        const initialTensor = stateToTensor(state);
        const expectedInitial = seq.snapshots[0].tensor;
        for (let j = 0; j < expectedInitial.length; j++) {
          if (Math.abs(initialTensor[j] - expectedInitial[j]) > 1e-6) {
            throw new Error(
              `${seq.name} initial tensor mismatch at index ${j}: ` +
              `TS=${initialTensor[j]}, Python=${expectedInitial[j]}`
            );
          }
        }

        // Apply each move and check tensor
        for (let i = 0; i < seq.moves.length; i++) {
          const moveAlg = seq.moves[i];
          const move = algebraicToMove(moveAlg);
          applyMove(state, move);

          const tsTensor = stateToTensor(state);
          const pyTensor = seq.snapshots[i + 1].tensor;

          for (let j = 0; j < pyTensor.length; j++) {
            if (Math.abs(tsTensor[j] - pyTensor[j]) > 1e-6) {
              throw new Error(
                `${seq.name} tensor mismatch at step ${i + 1} (${moveAlg}), index ${j}: ` +
                `TS=${tsTensor[j]}, Python=${pyTensor[j]}`
              );
            }
          }
        }
      });
    });
  }

  // Summary test
  it(`validates ${data.sequences.length} sequences with ${data.sequences.reduce((s, seq) => s + seq.snapshots.length, 0)} total snapshots`, () => {
    // This test just documents the coverage
    const totalSnapshots = data.sequences.reduce((s, seq) => s + seq.snapshots.length, 0);
    expect(totalSnapshots).toBeGreaterThan(200);
    expect(data.sequences.length).toBeGreaterThanOrEqual(8);
  });
});
