/**
 * Cross-validation test: TypeScript MCTS vs Python MCTS.
 *
 * Loads reference fixtures generated by generate_mcts_fixtures.py and verifies
 * the TypeScript MCTS produces identical results:
 * - Prior probabilities per child
 * - Visit counts per child
 * - Policy output from getPolicy(root, temp=1.0)
 */

import { describe, it, expect } from 'vitest';
import fixtures from './mcts-fixtures.json';
import { NUM_ACTIONS, END_TURN_ACTION } from '../bitboard';
import { getLegalMoves } from '../moves';
import { search, getPolicy, type MCTSConfig, type MCTSNode } from '../mcts';
import type { Evaluator } from '../evaluator';
import type { EngineState } from '../state';

// --- Deterministic evaluator matching Python's FixedValueEvaluator exactly ---

class FixedValueEvaluator implements Evaluator {
  async evaluate(
    state: EngineState,
  ): Promise<{ policy: Float32Array; value: number }> {
    const policy = new Float32Array(NUM_ACTIONS);
    const moves = getLegalMoves(state);
    for (const m of moves) {
      const idx = m === -1 ? END_TURN_ACTION : m;
      policy[idx] = 1.0;
    }
    let s = 0;
    for (let i = 0; i < policy.length; i++) s += policy[i];
    if (s > 0) {
      for (let i = 0; i < policy.length; i++) policy[i] /= s;
    }
    // Match Python: float(np.float32(0.1 * (state.ply % 5 - 2)))
    const value = Math.fround(0.1 * (state.ply % 5 - 2));
    return { policy, value };
  }
}

// --- Fixture types ---

interface FixtureState {
  pieces: [string, string];
  balls: [string, string];
  currentPlayer: number;
  touchedMask: string;
  hasPassed: boolean;
  lastKnightDst: number;
  ply: number;
}

interface FixtureChild {
  action: number;
  prior: number;
  visitCount: number;
  valueSum: number;
}

interface FixturePosition {
  state: FixtureState;
  children: FixtureChild[];
  policy: number[];
}

interface FixtureGame {
  gameSeed: number;
  numPositions: number;
  positions: FixturePosition[];
}

interface FixtureData {
  description: string;
  config: {
    numSimulations: number;
    batchSize: number;
    cPuct: number;
    temperature: number;
    earlyTermination: boolean;
    passQuiescence: boolean;
    dirichletEpsilon: number;
  };
  games: FixtureGame[];
}

const data = fixtures as FixtureData;

// --- Helpers ---

function fixtureToEngineState(fs: FixtureState): EngineState {
  return {
    pieces: [BigInt(fs.pieces[0]), BigInt(fs.pieces[1])],
    balls: [BigInt(fs.balls[0]), BigInt(fs.balls[1])],
    currentPlayer: fs.currentPlayer,
    touchedMask: BigInt(fs.touchedMask),
    hasPassed: fs.hasPassed,
    lastKnightDst: fs.lastKnightDst,
    ply: fs.ply,
  };
}

function getChildMap(root: MCTSNode): Map<number, MCTSNode> {
  return root.children;
}

// --- Tests ---

describe('MCTS cross-validation: TypeScript vs Python', () => {
  const evaluator = new FixedValueEvaluator();
  const mctsConfig: Partial<MCTSConfig> = {
    numSimulations: data.config.numSimulations,
    cPuct: data.config.cPuct,
    temperature: data.config.temperature,
    earlyTermination: data.config.earlyTermination,
    passQuiescence: data.config.passQuiescence,
    // Fixtures are generated with sequential Python MCTS (batch_size=1).
    // Without this, TS falls back to auto-batching with virtual loss and
    // visit counts diverge from the reference.
    batchSize: data.config.batchSize,
  };

  for (const game of data.games) {
    describe(`game seed ${game.gameSeed}`, () => {
      for (let posIdx = 0; posIdx < game.positions.length; posIdx++) {
        const fixture = game.positions[posIdx];

        it(`position ${posIdx} (ply=${fixture.state.ply})`, async () => {
          const state = fixtureToEngineState(fixture.state);

          const result = await search(state, evaluator, mctsConfig);
          const root = result.rootNode;

          // Compare children: priors, visit counts
          const tsChildren = getChildMap(root);
          const pyChildren = fixture.children;

          // Same number of children
          expect(tsChildren.size).toBe(
            pyChildren.length,
          );

          for (const pyChild of pyChildren) {
            const tsChild = tsChildren.get(pyChild.action);
            expect(tsChild).toBeDefined();
            if (!tsChild) continue;

            // Priors should match (float32 precision)
            expect(tsChild.prior).toBeCloseTo(pyChild.prior, 5);

            // Visit counts must match exactly
            expect(tsChild.visitCount).toBe(pyChild.visitCount);
          }

          // Compare policy output
          const tsPolicy = getPolicy(root, data.config.temperature);
          const pyPolicy = fixture.policy;

          expect(tsPolicy.length).toBe(pyPolicy.length);

          let maxDiff = 0;
          for (let i = 0; i < pyPolicy.length; i++) {
            const diff = Math.abs(tsPolicy[i] - pyPolicy[i]);
            if (diff > maxDiff) maxDiff = diff;
          }

          expect(maxDiff).toBe(0);
        });
      }
    });
  }

  it(`validates all ${data.games.length} games totalling ${data.games.reduce((s, g) => s + g.numPositions, 0)} positions`, () => {
    const totalPositions = data.games.reduce(
      (s, g) => s + g.numPositions,
      0,
    );
    expect(totalPositions).toBeGreaterThan(100);
    expect(data.games.length).toBe(10);
  });
});
